### ISSUE TITLE
TODO before release + open source

### ISSUE THREAD

**Issue by jackfranklin** [thread/custom-react-elements#1]
- [x] I think we can remove the mutation observer for _children_ and just make it care about attributes. We're not going to support external things modifying an element's children
- [x] Implement JSON parsing of attributes
- [x] Full project README
- [x] Example that polyfills the spec so it can run in IE11
- [x] Bundling the package nicely for all browsers. Rollup?
